의역
juliakorea/translate-doc pull request #13
Opened 2018-10-24 16:20 UTC by zmfkzj

이해하기 어려운 부분 원문과 비교하여 의역

2018-10-24 16:54 UTC, wookay requested changes

2018-10-24 16:54 UTC, wookay commented on src/manual/variables.md
> + a REPL 및 다른 여러 줄리아 편집 환경에서 많은 유니 코드 수학 기호를 입력 할 수 있습니다. 백 슬래쉬 + LaTeX 심볼 이름 다음에 탭을 입력하여 심볼을 입력하십시오.예를 를어 변수명 δ는 `\delta`-tab, `α^²`는 `\alpha`-tab-`\hat`-tab-`\_2`-tab 으로 입력할 수 있습니다. 어떤 기호를 입력하는 방법은
`a REPL` 이거랑 띄어쓰기도 좀 고쳐주실래요? `유니코드`,  `입력하십시오. 예를 들어`, `유니코드 기호를`  이런 식으로요.
원문은 https://github.com/juliakorea/translate-doc/blame/master/codex/manual/variables.md#L55  여기있습니다.  번역 개선에 참여해 주셔서 감사합니다.

2018-10-24 16:54 UTC, wookay commented on src/manual/variables.md
> + a REPL 및 다른 여러 줄리아 편집 환경에서 많은 유니 코드 수학 기호를 입력 할 수 있습니다. 백 슬래쉬 + LaTeX 심볼 이름 다음에 탭을 입력하여 심볼을 입력하십시오.예를 를어 변수명 δ는 `\delta`-tab, `α^²`는 `\alpha`-tab-`\hat`-tab-`\_2`-tab 으로 입력할 수 있습니다. 어떤 기호를 입력하는 방법은
아 원문 비교라 코멘트 하셨네요 :)

2018-10-24 17:02 UTC, zmfkzj commented on src/manual/variables.md
> + a REPL 및 다른 여러 줄리아 편집 환경에서 많은 유니 코드 수학 기호를 입력 할 수 있습니다. 백 슬래쉬 + LaTeX 심볼 이름 다음에 탭을 입력하여 심볼을 입력하십시오.예를 를어 변수명 δ는 `\delta`-tab, `α^²`는 `\alpha`-tab-`\hat`-tab-`\_2`-tab 으로 입력할 수 있습니다. 어떤 기호를 입력하는 방법은
깃허브는 눈팅밖에 안해봐서 뭐가 뭔지 모르겠네요... 눈에 띄는게 있으면 조금씩 수정해 보겠습니다.

2018-10-25 06:32 UTC, wookay commented on src/manual/variables.md
> +REPL 및 다른 여러 줄리아 편집 환경에서 많은 유니코드 수학 기호를 입력 할 수 있습니다. 백 슬래쉬 + LaTeX 기호명 다음에 탭을 입력하여 기호를 입력하십시오. 예를 들어 변수명 δ는 `\delta`-tab, `α^²`는 `\alpha`-tab-`\hat`-tab-`\_2`-tab 으로 입력할 수 있습니다. 어떤 기호를 입력하는 방법은 REPL에
`~~하십시오.` 대신에 `~~하세요.` 하면 좀 어색하지 않을 것 같아요.

2018-10-25 07:20 UTC, wookay approved these changes

2018-10-25 07:20 UTC, merged